{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "bl4code-frontend",
  // 更新为今天的日期
  "compatibility_date": "2025-09-30",
  "assets": {
    "directory": "./dist",
    "not_found_handling": "404-page" // 如果你有自定义的 `src/pages/404.astro` 页面
  }
}